Repository GongGang-A-Bapjwo/GongGang-A-Bapjwo-SERVER, pull requests merged in 2024-12, with the labels that each got.

#2 [feat] 프로젝트 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI-CD.yaml
  Dockerfile
  build.gradle
  src/main/java/com/example/gonggang/global/config/SecurityConfig.java
  src/main/java/com/example/gonggang/global/config/jasypt/JasyptConfig.java
  src/main/java/com/example/gonggang/global/config/swagger/SwaggerConfig.java
  src/main/java/com/example/gonggang/global/config/swagger/annotation/DisableSwaggerSecurity.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.properties
Labels: feat

#4 [fix] 배포 환경 변경
  .github/workflows/CI-CD.yaml
  .gitignore
  build.gradle
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: fix

#6 [feat] global 설정
  .gitignore
  src/main/java/com/example/gonggang/global/config/SecurityConfig.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/java/com/example/gonggang/global/config/error/ErrorResponse.java
  src/main/java/com/example/gonggang/global/config/error/exception/CustomAccessDeniedHandler.java
  src/main/java/com/example/gonggang/global/config/error/exception/GlobalExceptionHandler.java
  src/main/java/com/example/gonggang/global/config/error/exception/ServiceException.java
  src/main/java/com/example/gonggang/global/config/filter/ExceptionHandlerFilter.java
  src/main/java/com/example/gonggang/global/config/success/SuccessCode.java
Labels: feat

#9 [feat] 엔티티 설계 완료
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentBoard.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentParticipant.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentRoom.java
  src/main/java/com/example/gonggang/domain/common/BaseTimeEntity.java
  src/main/java/com/example/gonggang/domain/common/Category.java
  src/main/java/com/example/gonggang/domain/common/Weekday.java
  src/main/java/com/example/gonggang/domain/free_time/domain/FreeTime.java
  src/main/java/com/example/gonggang/domain/member/domain/Member.java
  src/main/java/com/example/gonggang/domain/member/domain/RegisterType.java
  src/main/java/com/example/gonggang/domain/member/domain/SocialType.java
  src/main/java/com/example/gonggang/domain/users/domain/Role.java
  src/main/java/com/example/gonggang/domain/users/domain/Users.java
  src/main/java/com/example/gonggang/global/config/audting/JpaAuditingConfig.java
Labels: feat

#10 [feat] 버킷 설정
  .github/workflows/CI-CD.yaml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/example/gonggang/domain/external/AmazonS3Manager.java
  src/main/java/com/example/gonggang/domain/external/exception/FileProcessingFailException.java
  src/main/java/com/example/gonggang/domain/external/exception/S3UploadFailException.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: feat

#16 [feat] 공강팟 생성 API 구현
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentParticipantSaveService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentRoomSaveService.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentBoard.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentRoom.java
  src/main/java/com/example/gonggang/domain/appointment/dto/request/AppointmentCreateRequest.java
  src/main/java/com/example/gonggang/domain/appointment/dto/response/AppointmentCreateResponse.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentParticipantRepository.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentRoomRepository.java
  src/main/java/com/example/gonggang/domain/users/exception/UserNotFoundException.java
  src/main/java/com/example/gonggang/domain/users/service/UserGetService.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/resources/application-local.yaml
Labels: feat

#18 [feat] 공강팟 참가 api 구현
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentRoomGetService.java
  src/main/java/com/example/gonggang/domain/appointment/application/ParticipantGetService.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentRoom.java
  src/main/java/com/example/gonggang/domain/appointment/dto/request/AppointmentEnterRequest.java
  src/main/java/com/example/gonggang/domain/appointment/exception/AlreadyEnteredException.java
  src/main/java/com/example/gonggang/domain/appointment/exception/AppointmentRoomMaxAppointmentException.java
  src/main/java/com/example/gonggang/domain/appointment/exception/AppointmentRoomNotFoundException.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentParticipantRepository.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentRoomRepository.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/java/com/example/gonggang/global/config/success/SuccessCode.java
Labels: feat

#22 [feat] 공강팟 조회&삭제 api 구현
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentRoomDeleteService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentRoomGetService.java
  src/main/java/com/example/gonggang/domain/appointment/application/ParticipantGetService.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentParticipant.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentRoom.java
  src/main/java/com/example/gonggang/domain/appointment/dto/response/AppointmentsGetResponse.java
  src/main/java/com/example/gonggang/domain/appointment/exception/ParticipantNotFoundException.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentParticipantRepository.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentRoomRepository.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
Labels: feat

#26 [feat] OpenFeign을 활용해 FastAPI 서버와 Spring 서버 간 통신 구현 및 공강 시간을 DB에 저장하는 기능 구현 완료
  src/main/java/com/example/gonggang/domain/common/Weekday.java
  src/main/java/com/example/gonggang/domain/common/exception/InvalidWeekdayException.java
  src/main/java/com/example/gonggang/domain/external/fast_api/application/FastApiService.java
  src/main/java/com/example/gonggang/domain/external/fast_api/feign/FastApiClient.java
  src/main/java/com/example/gonggang/domain/free_time/api/FreeTimeApi.java
  src/main/java/com/example/gonggang/domain/free_time/api/FreeTimeController.java
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeSaveService.java
  src/main/java/com/example/gonggang/domain/free_time/dto/response/FreeTimeResponse.java
  src/main/java/com/example/gonggang/domain/free_time/exception/OutputFirstElementIsNotMapException.java
  src/main/java/com/example/gonggang/domain/free_time/exception/OutputIsNotListException.java
  src/main/java/com/example/gonggang/domain/free_time/exception/OutputListIsEmptyException.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: feat

#30 [feat] 서버 인프라 변경
  build.gradle
  src/main/java/com/example/gonggang/global/config/SecurityConfig.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: feat

#32 [feat] 메인페이지 API 구현
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentBoardGetService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/dto/response/AppointmentAllResponse.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentBoardRepository.java
  src/main/java/com/example/gonggang/domain/common/Weekday.java
  src/main/java/com/example/gonggang/domain/free_time/api/FreeTimeController.java
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeGetService.java
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeManageService.java
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeSaveService.java
  src/main/java/com/example/gonggang/domain/free_time/dto/request/FreeTimeRequest.java
  src/main/java/com/example/gonggang/domain/free_time/dto/request/FreeTimeRequestItem.java
  src/main/java/com/example/gonggang/domain/free_time/dto/response/FreeTimeAllResponse.java
  src/main/java/com/example/gonggang/domain/free_time/dto/response/FreeTimeItem.java
  src/main/java/com/example/gonggang/domain/free_time/repository/FreeTimeRepository.java
  src/main/java/com/example/gonggang/global/config/WebConfig.java
  src/main/java/com/example/gonggang/global/config/success/SuccessCode.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: feat

#37 [feat] Admin을 위한 유저 삭제 기능, User를 위한 모든 약속 보기 구현
  src/main/java/com/example/gonggang/admin/api/AdminController.java
  src/main/java/com/example/gonggang/admin/application/AppointmentManagerService.java
  src/main/java/com/example/gonggang/admin/application/UserManageService.java
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentBoardGetService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentDeleteService.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentBoard.java
  src/main/java/com/example/gonggang/domain/appointment/dto/response/AllAppointmentBoardResponse.java
  src/main/java/com/example/gonggang/domain/appointment/dto/response/AppointmentCreateResponse.java
  src/main/java/com/example/gonggang/domain/appointment/exception/AppointmentBoardNotFoundException.java
  src/main/java/com/example/gonggang/domain/appointment/repository/AppointmentBoardRepository.java
  src/main/java/com/example/gonggang/domain/member/application/MemberService.java
  src/main/java/com/example/gonggang/domain/member/repository/MemberRepository.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/java/com/example/gonggang/global/config/success/SuccessCode.java
Labels: feat

#38 [feat] fastAPI 서버로 openfeign을 통해 입장코드를 보내는 기능 완료
  src/main/java/com/example/gonggang/admin/api/AdminController.java
  src/main/java/com/example/gonggang/admin/domain/Admin.java
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/domain/AppointmentParticipant.java
  src/main/java/com/example/gonggang/domain/external/fast_api/application/FastApiService.java
  src/main/java/com/example/gonggang/domain/external/fast_api/dto/FastApiResponse.java
  src/main/java/com/example/gonggang/domain/external/fast_api/feign/FastApiClient.java
  src/main/java/com/example/gonggang/domain/free_time/api/FreeTimeController.java
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeSaveService.java
  src/main/java/com/example/gonggang/domain/free_time/domain/FreeTime.java
  src/main/java/com/example/gonggang/domain/member/domain/Member.java
Labels: feat

#41 [feat] 공팟원들이 입장코드를 통해 입장할 때, openfeign으로 fastAPI 서버에 입장 코드를 보내는 기능 구현 완료
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/dto/response/AppointmentEntranceResponse.java
Labels: feat

#43 [feat] openfegin을 활용해 fastAPI의 시간잡기 API로 요청하는 API 구현 완료
  src/main/java/com/example/gonggang/domain/appointment/api/AppointmentController.java
  src/main/java/com/example/gonggang/domain/appointment/application/AppointmentManageService.java
  src/main/java/com/example/gonggang/domain/appointment/dto/request/AppointmentExtractTimeRequest.java
  src/main/java/com/example/gonggang/domain/external/fast_api/application/FastApiService.java
  src/main/java/com/example/gonggang/domain/external/fast_api/feign/FastApiClient.java
  src/main/java/com/example/gonggang/domain/external/fast_api/util/TimeFormater.java
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeSaveService.java
Labels: feat

#47 [refactor] 카카오 로그인 redirect-uri 변경
  src/main/resources/application-prod.yaml
Labels: refactor

#49 [feat] 로그 출력용 AOP 구현 완료
  build.gradle
  src/main/java/com/example/gonggang/global/aop/ExecutionLoggingAop.java
Labels: feat

#53 [refactor] 시간표 업로드 시 기존 시간표를 삭제 후 업로드 하도록 변경
  src/main/java/com/example/gonggang/domain/free_time/application/FreeTimeSaveService.java
  src/main/java/com/example/gonggang/domain/free_time/repository/FreeTimeRepository.java
Labels: refactor

#55 [feat] Sentry 에러 모니터링 툴 구축
  build.gradle
  src/main/java/com/example/gonggang/global/config/SecurityConfig.java
  src/main/java/com/example/gonggang/global/config/error/ErrorCode.java
  src/main/java/com/example/gonggang/global/config/error/exception/GlobalExceptionHandler.java
  src/main/java/com/example/gonggang/global/config/sentry/SentryConfig.java
  src/main/java/com/example/gonggang/global/config/sentry/SentryController.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/console-appender.xml
  src/main/resources/logback-spring.xml
Labels: feat
